code-for-hamamatsu/vaccinecert-faq

- .gitmodules
- close https://github.com/code-for-hamamatsu/vaccinecert-faq/issues/2
- https://github.com/code-for-hamamatsu/vaccinecert-faq/commit/68a0313c4f9966b707990acd6589e10f6544e796
自身のアカウントにて効果確認済みです。
> Amplify Consoleでデプロイできるようにする

- config.toml
Home の url を空にした
- close #4
- `config.toml` の日本語・英語の "Home" の url を空に
> ナビゲーションバー「HOME」リンク先不具合修正

- Dockerfile
- README.md
- docker-compose.yml
- close #1 
- Dockerでhugoの開発環境を起動できるようにした
- READMEにDockerでの起動方法について追記、合わせて初回起動時に少しハマった `git submodule update` についても記載
> Dockerで起動できるようにする

- config.toml
- close #8
- config.toml のデフォルト言語設定の書き方を修正
- 設定値はスネークケースかつ記述位置も重要だった様子
> refs#8 set default language to Japanese

- layouts/partials/default.html
- close #19
- サイドバーを削除
- PC
- モバイル
> refs #19 サイドバーを削除

- config.toml
- content/about/_index.ja.md
デジタル庁の問い合わせフォームURL待ち
- close #20
- close #24
- Aboutページを追加
- ヘッダ部のリンクにAboutを追加
> Aboutページ仮実装

- layouts/partials/default.html
- close #30
- カテゴリ別ページの無意味な更新日（1 年 1 月 1 日）が表示されないようにした
> refs #30 無意味な更新日を消す

- layouts/partials/banner.html
- close #6
- トップページ（Home）のバナーにある検索窓を非表示に
- 関連部分全体をコメントアウトしてあります
> refs #6 検索窓を一旦非表示に

- layouts/shortcodes/vaccinefaq.html
- close #14 
- 回答のdivに対して style="white-space:pre-wrap; を当てる。 https://github.com/code-for-hamamatsu/vaccinecert-faq/commit/07595ca164723a0a455ac9a15d46a75b6723907d
対応前
対応後
> FAQ回答の改行が反映されていない。 #14 への対応

- config.toml
- close #13 
- config.toml にて `subtitle` をコメントアウトした
> サブタイトルを非表示にする

- config.toml
- close #15
- config.toml disableLanguages = ["en"] を設定
- xxx
> enを使用しない設定にした

- content/about/_index.ja.md
マージしていただいたのですが、もう少し修正させてください @muraさんの指摘追加です
- close #20 
- 以下のスクリーンショットのようになります
> Aboutページの表記内容再度修正

- config.toml
- close #46
- close #0
- #0
- #0
- footerのコピーライト表示を Code For Hamamatsuにする
> フッタのコピーライト表示を修正

- layouts/shortcodes/vaccinefaq.html
- close #38
- Q&A の最終更新日を表示
- 日付のフォーマットは本文に出てくるものに合わせました。
> refs #38 Q&A の最終更新日を表示

- config.toml
#51 の一部。まだCloseはしない。
config.toml の description を 以下とする。
```
このサイトはデジタル庁が公開した新型コロナワクチン接種証明書アプリのFAQサイトです。
```
以下のキャプチャにある 「This is meta description」が適切ではないため修正します。
> SNSでシェアしたときに、適切に情報が出るようにする #51 (説明)

- layouts/partials/head.html
- close #51
- #0
- #0
- Twitter のカードサイズを小に
> Twitter のカードサイズを小に

- config.toml
- close #51 
- #0
- #0
- xxxxxx
- xxx
> OGP 画像パス指定を戻した（head.html の指定が使われるように）

- content/about/_index.ja.md
- close #58
- お問い合わせフォームに関する記述のコメント外した
- お問い合わせフォームのタイトルとの表記を合わせた
クリックで以下ページ開くこと確認
> お問い合わせフォームに関する記述のコメント外した

- README.md
マージはファーストリリースの後でもよいかも
- close #43
- 本番サイトのURLを載せた
- xxx
> 本番サイトのURLを記載

- layouts/shortcodes/vaccinefaq.html
- close #52
- hugoのFunction markdownfyを用いてURLと認識させた
https://gohugo.io/functions/markdownify/
> 回答に含まれるURLを有効にする

- README.md
- close #69
- close #0
- #42
- #0
こういう風に変更
| 種類 | ブランチのネーミングルール |
| ---- | ---- |
|機能追加系|`feature/{ISSUE_ID}-{branch_title_name}`|
|ホットフィックス系|`fix/{ISSUE_ID}-{branch_title_name}`|
> ブランチ名ルール変更

- layouts/partials/navigation.html
- close #62
- トップ画面→ヘッダのタイトルを非表示に
- その他→ヘッダのタイトルとハンバーガーメニューアイコンの隙間を 8px に狭めて改行されにくいように
- トップページ
- その他
> refs #62 ヘッダのハンバーガーメニュー調整

- content/search/_index.ja.md
> refs #71 検索窓の幅を調整

- .github/workflows/csv2json.yml
- data/faq/faq.json
- tool/data-converter/main.py
- tool/data-converter/requirements.txt
- #11 (AutoMergeラベル付きのプルリクを発行するところまで)
- オープンデータ(csv)からjson変換するpython
- 定期実行するActions (3時間おきにしているが時間は要検討) (手動実行可)
発行されたプルリク
https://github.com/ww2or3ww/vaccinecert-faq/pull/5
シークレットへ `TOKEN_GITHUB` を登録する必要あり。
定期実行の間隔は要相談
> オープンデータのCSVをjsonに自動で変換するようにしたい #11 (プルリクまで)

- content/about/_index.ja.md
- close #84
- URL 部分のみ `word-wrap` 等を指定して改行するようにした
> refs #84 ABOUT の参照先オープンデータ URL を途中で改行するように

- layouts/shortcodes/faq.html
- layouts/shortcodes/result.html
- close #90
- 検索結果画面からのリンクに「?back=search」を付加
- 個別 QA ページ表示時にこのリクエストパラメータが付いていたらリンクの表記と内容を変更
- その他見た目の微修正
> 個別 QA ページから検索結果ページへ戻れるようにする

- layouts/shortcodes/faq.html
- layouts/shortcodes/faqlist.html
- layouts/shortcodes/result.html
- close #94 
- 画面遷移時のアドレス末尾に/を付ける
> 個別 QA ページから検索結果ページへ戻れるようにする #92 が本番環境だと機能しない #94 の解決

- config.toml
- close #98
- config.tomlのbaseURLをローカルホストに変更 ()
``` toml
baseURL = "http://localhost:1313/"
```
> デフォルトのbaseURLをローカルホストに変更

- content/search/_index.ja.md
- close #103
- 検索キーワードと検索対象（質問・回答）の文字列に対して以下の正規化を実装
- 全角英数字・記号→半角化
- ひらがな→全角カタカナ化
- 半角カナ→同上
- その他の揺らぎ（「一回」→「1回」など）、入力ミス（「摂取」→「接種」など）の吸収
> 検索キーワードの処理修正＋正規化の実装

- tool/data-creator/csv2json.py
- close #604
- csv読込のデコード utf-8 で失敗したら shift_jis でリトライする。
> csvデータの読み込み処理に失敗している #604 対応
